version: '3.4'

volumes:
  postgresql-db:
    driver: local
  certs:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: pleroma-nginx
    expose:
      - "20091"
    restart: always
    tty: false
    environment:
      - VIRTUAL_HOST=${PLEROMA_HOSTNAME}
      - VIRTUAL_PORT=${PLEROMA_VIRTUAL_PORT}
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=${PLEROMA_HOSTNAME}
      - LETSENCRYPT_EMAIL=${PLEROMA_LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=false
    links:
      - web
    depends_on:
      - web
    volumes:
      - ./setting/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./setting/nginx/templates:/etc/nginx/tem
      - certs:/etc/nginx/certs
    networks:
      - front
      - back-pleroma

  db:
    restart: always
    image: postgres:9.6-alpine
    container_name: pleroma-db
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: ${PLEROMA_DB_PASSWORD}
      POSTGRES_DB: pleroma
    volumes:
      - ${PLEROMA_DB_DIR}:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - back-pleroma

  web:
    build: docker/otp/.
    image: pleroma
    #container_name: pleroma_web
    restart: always
    environment:
      MIX_ENV: prod
    ports:
      - '127.0.0.1:4000:4000'
    volumes:
      - ./data/pleroma/content/uploads:/var/lib/pleroma/uploads
      - ./pleroma-custom/priv/static:/var/lib/pleroma/static
      - ./setting/web/config/prod.secret.exs:/etc/pleroma/config.exs:ro
    depends_on:
      - db
    networks:
      - front
      - back-pleroma

networks:
  front:
    external: true
  back-pleroma:
    external: true
